### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by sioban** [CaliDog/certstream-js#2] opened 2017-11-08 12:47 UTC
Hi,

I have this error when I try to run Certstream:
# certstream
[ERROR:websocket] 2017-11-08 12:42:31,774 - error from callback <bound method CertStreamClient._on_error of <certstream.core.CertStreamClient object at 0x1926a90>>: maximum recursion depth exceeded while calling a Python object

Any idea why ?

**Comment by Fitblip** [comment] 2017-11-08 22:45
Hey @sioban - This is an issue caused by a bug in the https://github.com/CaliDog/certstream-python project (calidog/certstream-python#2 - specifically fixed with https://github.com/CaliDog/certstream-python/commit/e7dd15eec14a9ab4769c5de965d2d5f7ec9aa712).

If you upgrade your certstream installation (`pip install --upgrade certstream`), then things should be fine!

**Comment by Fitblip** [comment] 2018-02-19 00:13
This is long fixed, sorry for the stale bug!

**Closed as completed by Fitblip** 2018-02-19 00:13 UTC
